### ISSUE TITLE
Cannot find modules in in18nextify/example

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18nextify#1]
Hi. I think since you have done some refactor in your module i18next, you have probably forgot to update your example here. When lauching your example with `node server.js`, we have the following errors:

```
C:\test\i18nextify-master\example>node server.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'i18next/lib'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\test\i18nextify-master\example\server.js:1:77)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

By looking in the file server.js, you have the following line (The first one ):

`var i18next = require('i18next/lib');`

Because you don't have the lib folder anymore in your i18next module, I guess that the solution is just to replace this line with:

`var i18next = require('i18next');`

I've tried this and it looks to work well.. :-)

Thank you

**Comment by jamuhl** [comment]
yes...correct...will update asap
